version: '3'
services:
  app:
    build:
      context: ./docker/app
      args:
        uid: ${APP_UID}
        gid: ${APP_GID}
    environment:
      PS1: '\u@\h:\w\$$ '
      TZ: Asia/Tokyo
    env_file: .env
    working_dir: /app
    volumes:
      - .:/app
      - ./vendor/bundle:/usr/local/bundle
    command: bash -c 'rm -f tmp/pids/server.pid; rails s -b 0.0.0.0'
    depends_on:
      - db
    logging:
      options:
        max-size: 10m
        max-file: '10'
  db:
    build:
      context: ./docker/db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=C'
      TZ: Asia/Tokyo
    ports:
      - '${PUBLISH_DATABASE_PORT}:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./backup:/backup
    logging:
      options:
        max-size: 10m
        max-file: '10'
  web:
    build:
      context: ./docker/web
    environment:
      TZ: Asia/Tokyo
    ports:
      - '${PUBLISH_WEB_SERVER_PORT}:80'
    volumes:
      - ./log/nginx:/var/log/nginx
    depends_on:
      - app
    logging:
      options:
        max-size: 10m
        max-file: '10'
volumes:
  db:
