version: '3'
services:
  app:
    build:
      context: './docker/app'
      args:
        uid: ${APP_UID}
        gid: ${APP_GID}
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: ${RAILS_ENV}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      RAILS_SERVE_STATIC_FILES: ${RAILS_SERVE_STATIC_FILES}
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - ./vendor/bundle:/usr/local/bundle
    ports:
      - '3000:3000'
    command: rails s -b 0.0.0.0
    depends_on:
      - db
  db:
    image: postgres:9.6.8
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD:
      TZ: Asia/Tokyo
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./backup:/backup
  web:
    image: nginx:1.13.9
    environment:
      TZ: Asia/Tokyo
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx
      - ./log/nginx:/var/log/nginx
    depends_on:
      - app
volumes:
  db:
