version: '3'
services:
  app:
    environment:
      RAILS_ENV: development
    command: bash -c 'rm -f tmp/pids/server.pid; rails s -b 0.0.0.0 & bin/webpack-dev-server'
    ports:
      - 3035:3035
  db:
    ports:
      - '${PUBLISH_DATABASE_PORT}:5432'
